version: '3'

services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --providers.docker.exposedbydefault=false
    networks:
      - web
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    networks:
      - web
    volumes:
      - ./mongo/db:/data/db
    labels: 
      - "traefik.enable=true"
  api:
    build: ./api
    networks:
      - web
    labels: 
      - traefik.enable=true
      - traefik.http.routers.api-http.rule=Host(`api.localhost`)
      - traefik.http.routers.api-http.rule=PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)
      - traefik.http.routers.api-http.middlewares=api-stripprefix@docker
      - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.api-stripprefix.stripprefix.forceSlash=false
    depends_on: 
      - mongodb
  frontend:
    build: ./frontend
    networks:
      - web
    labels: 
      - traefik.enable=true
      - traefik.http.routers.frontend-http.rule=PathPrefix(`/`)
networks:
  web:
    driver: bridge
